version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge